service: cardcom-webhook-listener
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  timeout: 60
  environment:
    SF_LOGIN_URL: ${env:SF_LOGIN_URL}
    SF_USERNAME:  ${env:SF_USERNAME}
    SF_PASSWORD:  ${env:SF_PASSWORD}
    CARDCOM_SECRET: ${env:CARDCOM_SECRET}
functions:
  recurringDonationWebhookListener:
    handler: handler.recurringDonationWebhookListener
    events:
      - http:
          path: recurringDonationWebhookListener
          method: post
          cors: true
  donationWebhookListener:
    handler: handler.donationWebhookListener
    events:
      - http:
          path: donationWebhookListener
          method: post
          cors: true